package com.example.modules.activity.entity;

import java.io.Serializable;
import java.util.Date;

public class Activity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_name
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.manager_name
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    private String managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.manager_id
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    private Integer managerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.address
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.start_time
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.end_time
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.num
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.max_num
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    private Integer maxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.status
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_name
     *
     * @return the value of activity.activity_name
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_name
     *
     * @param activityName the value for activity.activity_name
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.manager_name
     *
     * @return the value of activity.manager_name
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.manager_name
     *
     * @param managerName the value for activity.manager_name
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.manager_id
     *
     * @return the value of activity.manager_id
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.manager_id
     *
     * @param managerId the value for activity.manager_id
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.address
     *
     * @return the value of activity.address
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.address
     *
     * @param address the value for activity.address
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.start_time
     *
     * @return the value of activity.start_time
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.start_time
     *
     * @param startTime the value for activity.start_time
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_time
     *
     * @return the value of activity.end_time
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_time
     *
     * @param endTime the value for activity.end_time
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.num
     *
     * @return the value of activity.num
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.num
     *
     * @param num the value for activity.num
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.max_num
     *
     * @return the value of activity.max_num
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public Integer getMaxNum() {
        return maxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.max_num
     *
     * @param maxNum the value for activity.max_num
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public void setMaxNum(Integer maxNum) {
        this.maxNum = maxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.status
     *
     * @return the value of activity.status
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.status
     *
     * @param status the value for activity.status
     *
     * @mbggenerated Fri Apr 24 17:20:11 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}