package com.example.modules.activity.entity;

import java.io.Serializable;

public class Activity implements Serializable {

    private Integer id;

    private String activityName;

    private String managerName;

    private Integer managerId;

    private String address;

    private String startTime;

    private String endTime;

    private Integer num;

    private Integer maxNum;

    private Integer visit;

    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_name
     *
     * @return the value of activity.activity_name
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_name
     *
     * @param activityName the value for activity.activity_name
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.manager_name
     *
     * @return the value of activity.manager_name
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.manager_name
     *
     * @param managerName the value for activity.manager_name
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.manager_id
     *
     * @return the value of activity.manager_id
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.manager_id
     *
     * @param managerId the value for activity.manager_id
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.address
     *
     * @return the value of activity.address
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.address
     *
     * @param address the value for activity.address
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.start_time
     *
     * @return the value of activity.start_time
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.start_time
     *
     * @param startTime the value for activity.start_time
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_time
     *
     * @return the value of activity.end_time
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_time
     *
     * @param endTime the value for activity.end_time
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.num
     *
     * @return the value of activity.num
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.num
     *
     * @param num the value for activity.num
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.max_num
     *
     * @return the value of activity.max_num
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public Integer getMaxNum() {
        return maxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.max_num
     *
     * @param maxNum the value for activity.max_num
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public void setMaxNum(Integer maxNum) {
        this.maxNum = maxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.visit
     *
     * @return the value of activity.visit
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public Integer getVisit() {
        return visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.visit
     *
     * @param visit the value for activity.visit
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public void setVisit(Integer visit) {
        this.visit = visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.status
     *
     * @return the value of activity.status
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.status
     *
     * @param status the value for activity.status
     *
     * @mbggenerated Thu May 07 12:59:02 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    public Activity() {
    }

    public Activity(String activityName, String managerName, Integer managerId, String address, String startTime, String endTime, Integer num, Integer maxNum, Integer visit, Integer status) {
        this.activityName = activityName;
        this.managerName = managerName;
        this.managerId = managerId;
        this.address = address;
        this.startTime = startTime;
        this.endTime = endTime;
        this.num = num;
        this.maxNum = maxNum;
        this.visit = visit;
        this.status = status;
    }
}