server:
  port: 8088
  servlet:
    context-path: /Activity_System
spring:
  datasource:
    name: test
    url: jdbc:mysql://47.106.141.174:3306/storage?serverTimezone=UTC
    username: root
    password: 123456

logging:
  config: log4j2-spring.xml
  logging:
    level:
      com:
       example:
        modules:
         activity:
           mapper: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
