server:
  port: 8088
  servlet:
    context-path: /Activity_System
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/shiro
    username: root
    password: Loveshiro!

logging:
  config: src\main\resources\log4j2-spring.xml
  logging:
    level:
      com:
       example:
        modules:
         activity:
           mapper: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl